const config={type:Phaser.AUTO,width:960,height:540,backgroundColor:'#11151d',physics:{default:'arcade',arcade:{debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:{create,update}};new Phaser.Game(config);
let player,weapon,cursors,enemies,hp=100,maxHp=100,xp=0,level=1,points=0,hud,statsText,lastAttack=0,lastSkill=0,gameStarted=false,playerClass='',radar,radarDots=[];
let stats={str:10,agi:10,vit:10,ene:10},joyBase,joyKnob,joyDir=new Phaser.Math.Vector2(),joyPointer=null,facing=new Phaser.Math.Vector2(1,0),isSwinging=false,playerName,playerHpBg,playerHpBar;
const monsterNames=['Goblin','Dark Wolf','Orc','Skeleton','Imp','Demon Rat'];const classes={Warrior:{color:0xcda85b,hp:130,str:18,agi:10,vit:15,ene:5},Wizard:{color:0x5b8fc9,hp:90,str:5,agi:10,vit:8,ene:22},Archer:{color:0x58a66b,hp:105,str:10,agi:20,vit:10,ene:8}};
function create(){const g=this.add.graphics();g.fillStyle(0x182019).fillRect(0,0,960,540);g.lineStyle(1,0x263328,.35);for(let x=0;x<960;x+=32)g.lineBetween(x,0,x,540);for(let y=0;y<540;y+=32)g.lineBetween(0,y,960,y);makeForest(this);showClassSelect(this);}
function makeForest(s){for(let i=0;i<32;i++){let x=Phaser.Math.Between(25,935),y=Phaser.Math.Between(65,510);if(Phaser.Math.Distance.Between(x,y,480,270)<100){i--;continue}let trunk=s.add.rectangle(x,y+11,8,18,0x5a3822).setDepth(1),crown=s.add.circle(x,y,Phaser.Math.Between(15,22),Phaser.Utils.Array.GetRandom([0x244c2a,0x2e5c32,0x356b38])).setStrokeStyle(3,0x17351d).setDepth(2);s.add.circle(x-6,y-5,5,0x487b43,.7).setDepth(3);}}
function showClassSelect(s){s.add.rectangle(480,270,700,390,0x080a0e,.94).setStrokeStyle(3,0x8b6b32).setDepth(50);s.add.text(480,115,'CHOOSE YOUR CLASS',{fontFamily:'monospace',fontSize:'28px',color:'#f3d27a'}).setOrigin(.5).setDepth(51);[['Warrior','SWORD'],['Wizard','STAFF'],['Archer','BOW']].forEach((c,i)=>{let x=270+i*210,b=s.add.circle(x,260,70,classes[c[0]].color,.9).setStrokeStyle(5,0x493a20).setDepth(51).setInteractive();s.add.text(x,355,`${c[0]}\n${c[1]}`,{align:'center',fontFamily:'monospace',fontSize:'16px',color:'#fff'}).setOrigin(.5).setDepth(51);b.on('pointerdown',()=>startGame(s,c[0]));});}
function startGame(s,c){playerClass=c;let d=classes[c];maxHp=d.hp;hp=maxHp;stats={str:d.str,agi:d.agi,vit:d.vit,ene:d.ene};s.children.list.filter(o=>o.depth>=50).forEach(o=>o.destroy());player=s.add.circle(480,270,18,d.color).setStrokeStyle(4,0x352b1c);s.physics.add.existing(player);player.body.setCircle(18).setCollideWorldBounds(true);weapon=s.add.rectangle(510,270,c==='Archer'?30:36,c==='Wizard'?7:8,c==='Wizard'?0x9c7bd6:c==='Archer'?0x9b6b3d:0xd7dbe0).setStrokeStyle(2,0x4b5563).setOrigin(.15,.5).setDepth(4);playerName=s.add.text(480,238,'',{fontFamily:'monospace',fontSize:'12px',color:'#f6e5b3'}).setOrigin(.5).setDepth(6);playerHpBg=s.add.rectangle(480,250,48,6,0x260b0b).setDepth(6);playerHpBar=s.add.rectangle(456,250,48,6,0x35b64a).setOrigin(0,.5).setDepth(7);cursors=s.input.keyboard.createCursorKeys();s.keys=s.input.keyboard.addKeys('W,A,S,D,SPACE,Q');enemies=s.physics.add.group();for(let i=0;i<12;i++)spawnEnemy(s);hud=s.add.text(14,12,'',{fontFamily:'monospace',fontSize:'17px',color:'#f3d27a'}).setDepth(20);statsText=s.add.text(14,38,'',{fontFamily:'monospace',fontSize:'13px',color:'#ddd'}).setDepth(20);setupTouchControls(s);createRadar(s);gameStarted=true;}
function createRadar(s){radar=s.add.graphics().setDepth(35);}
function drawRadar(){radar.clear();radar.fillStyle(0x05080a,.82).fillCircle(875,90,65);radar.lineStyle(3,0x9a8149,.9).strokeCircle(875,90,65);radar.lineStyle(1,0x53604d,.45).strokeCircle(875,90,35);radar.fillStyle(0x52d66b,1).fillCircle(875,90,4);enemies.children.iterate(e=>{if(!e)return;let dx=(e.x-player.x)*.22,dy=(e.y-player.y)*.22,d=Math.sqrt(dx*dx+dy*dy);if(d>58){dx*=58/d;dy*=58/d}radar.fillStyle(0xe44b4b,1).fillCircle(875+dx,90+dy,3)});}
function setupTouchControls(s){joyBase=s.add.circle(105,435,62,0x000000,.35).setStrokeStyle(3,0x8e7947,.8).setDepth(30);joyKnob=s.add.circle(105,435,28,0xc2a55b,.65).setDepth(31);joyBase.setInteractive(new Phaser.Geom.Circle(62,62,62),Phaser.Geom.Circle.Contains);joyBase.on('pointerdown',p=>{joyPointer=p.id;updateJoy(p)});s.input.on('pointermove',p=>{if(p.id===joyPointer&&p.isDown)updateJoy(p)});s.input.on('pointerup',p=>{if(p.id===joyPointer){joyPointer=null;joyDir.set(0,0);joyKnob.setPosition(105,435)}});let a=s.add.circle(850,430,52,0x7c2d2d,.8).setStrokeStyle(3,0xe07a5f).setDepth(30).setInteractive();s.add.text(850,430,'ATK',{fontFamily:'monospace',fontSize:'18px',color:'#fff'}).setOrigin(.5).setDepth(31);a.on('pointerdown',()=>attack(s));let sk=s.add.circle(755,455,38,0x2f5d78,.85).setStrokeStyle(3,0x76c7c0).setDepth(30).setInteractive();s.add.text(755,455,'SKILL',{fontFamily:'monospace',fontSize:'12px',color:'#fff'}).setOrigin(.5).setDepth(31);sk.on('pointerdown',()=>skill(s));let st=s.add.text(690,20,'STATS +',{fontFamily:'monospace',fontSize:'15px',backgroundColor:'#49391f',padding:{x:8,y:5},color:'#ffd77a'}).setDepth(30).setInteractive();st.on('pointerdown',()=>openStats(s));}
function openStats(s){if(s.statPanel){s.statPanel.forEach(o=>o.destroy());s.statPanel=null;return}let arr=[],bg=s.add.rectangle(790,190,300,210,0x090b10,.96).setStrokeStyle(2,0x8b6b32).setDepth(40);arr.push(bg);let t=s.add.text(665,105,`STAT POINTS: ${points}`,{fontFamily:'monospace',fontSize:'16px',color:'#f3d27a'}).setDepth(41);arr.push(t);[['STR','str'],['AGI','agi'],['VIT','vit'],['ENE','ene']].forEach((v,i)=>{let y=140+i*35,tx=s.add.text(675,y,`${v[0]}: ${stats[v[1]]}`,{fontFamily:'monospace',fontSize:'15px',color:'#fff'}).setDepth(41),b=s.add.text(875,y,'+',{fontFamily:'monospace',fontSize:'20px',backgroundColor:'#59451f',padding:{x:8,y:1},color:'#ffd77a'}).setDepth(41).setInteractive();b.on('pointerdown',()=>{if(points>0){points--;stats[v[1]]++;if(v[1]==='vit'){maxHp+=3;hp+=3}openStats(s);openStats(s)}});arr.push(tx,b)});s.statPanel=arr;}
function updateJoy(p){let d=new Phaser.Math.Vector2(p.x-105,p.y-435);if(d.length()>55)d.setLength(55);joyKnob.setPosition(105+d.x,435+d.y);joyDir=d.clone().scale(1/55);}
function spawnEnemy(s){let e=s.add.circle(Phaser.Math.Between(50,910),Phaser.Math.Between(65,485),14,0x8f2d38).setStrokeStyle(3,0x3f1017);s.physics.add.existing(e);e.body.setCircle(14);e.maxHp=Phaser.Math.Between(45,80);e.hp=e.maxHp;e.monsterName=Phaser.Utils.Array.GetRandom(monsterNames);e.nameText=s.add.text(e.x,e.y-29,e.monsterName,{fontFamily:'monospace',fontSize:'10px',color:'#e5c7c7'}).setOrigin(.5).setDepth(5);e.hpBg=s.add.rectangle(e.x,e.y-20,36,5,0x260b0b).setDepth(5);e.hpBar=s.add.rectangle(e.x-18,e.y-20,36,5,0xd04444).setOrigin(0,.5).setDepth(6);enemies.add(e);}
function update(time){if(!gameStarted)return;let dx=(cursors.left.isDown||this.keys.A.isDown?-1:0)+(cursors.right.isDown||this.keys.D.isDown?1:0),dy=(cursors.up.isDown||this.keys.W.isDown?-1:0)+(cursors.down.isDown||this.keys.S.isDown?1:0),v=new Phaser.Math.Vector2(dx,dy);if(joyDir.lengthSq()>.01)v.copy(joyDir);if(v.lengthSq()){v.normalize();facing.copy(v);player.body.setVelocity(v.x*(180+stats.agi*1.2),v.y*(180+stats.agi*1.2))}else player.body.setVelocity(0);if(!isSwinging)placeWeapon();if(Phaser.Input.Keyboard.JustDown(this.keys.SPACE))attack(this,time);if(Phaser.Input.Keyboard.JustDown(this.keys.Q))skill(this,time);enemies.children.iterate(e=>{if(!e)return;let d=Phaser.Math.Distance.Between(e.x,e.y,player.x,player.y);if(d<220){this.physics.moveToObject(e,player,55);if(d<33&&time>(e.hitAt||0)){e.hitAt=time+800;hp=Math.max(0,hp-8);if(!hp){hp=maxHp;player.setPosition(480,270)}}}else e.body.setVelocity(0);updateEnemyUi(e)});updatePlayerUi();drawRadar();hud.setText(`${playerClass.toUpperCase()}  LV ${level}  HP ${hp}/${maxHp}  XP ${xp}/${level*100}  POINTS ${points}`);statsText.setText(`STR ${stats.str}  AGI ${stats.agi}  VIT ${stats.vit}  ENE ${stats.ene}`);}
function updatePlayerUi(){playerName.setPosition(player.x,player.y-32).setText(`${playerClass} Lv.${level}`);playerHpBg.setPosition(player.x,player.y-22);playerHpBar.setPosition(player.x-24,player.y-22).displayWidth=48*hp/maxHp;}
function updateEnemyUi(e){if(!e.active)return;e.nameText.setPosition(e.x,e.y-29);e.hpBg.setPosition(e.x,e.y-20);e.hpBar.setPosition(e.x-18,e.y-20);e.hpBar.displayWidth=36*Math.max(0,e.hp/e.maxHp);}
function placeWeapon(){let a=facing.angle();weapon.setPosition(player.x+facing.x*17,player.y+facing.y*17);weapon.rotation=a;}
function attack(s,time=performance.now()){if(time-lastAttack<350)return;lastAttack=time;isSwinging=true;let base=facing.angle();weapon.rotation=base-.8;s.tweens.add({targets:weapon,rotation:base+.9,duration:150,yoyo:true,onComplete:()=>{isSwinging=false;placeWeapon()}});let range=playerClass==='Archer'?120:playerClass==='Wizard'?90:72,damage=playerClass==='Wizard'?12+stats.ene*1.5:playerClass==='Archer'?12+stats.agi:15+stats.str;enemies.children.iterate(e=>{if(e&&Phaser.Math.Distance.Between(e.x,e.y,player.x,player.y)<range){e.hp-=damage;updateEnemyUi(e);if(e.hp<=0)killEnemy(s,e)}});}
function skill(s,time=performance.now()){if(time-lastSkill<2200)return;lastSkill=time;let ring=s.add.circle(player.x,player.y,20,0x56cfe1,.18).setStrokeStyle(4,0x56cfe1).setDepth(2);s.tweens.add({targets:ring,scaleX:5,scaleY:5,alpha:0,duration:320,onComplete:()=>ring.destroy()});let dmg=25+stats.ene*2;enemies.children.iterate(e=>{if(e&&Phaser.Math.Distance.Between(e.x,e.y,player.x,player.y)<110){e.hp-=dmg;if(e.hp<=0)killEnemy(s,e)}});}
function killEnemy(s,e){if(!e.active)return;e.nameText.destroy();e.hpBg.destroy();e.hpBar.destroy();e.destroy();xp+=25;while(xp>=level*100){xp-=level*100;level++;points+=5;hp=maxHp}s.time.delayedCall(900,()=>spawnEnemy(s));}
