const config={type:Phaser.AUTO,width:960,height:540,backgroundColor:'#182019',physics:{default:'arcade'},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:{create,update}};new Phaser.Game(config);
let S,player,enemies,trees,loots,joyBase,joyKnob,joyDir=new Phaser.Math.Vector2(),joyPointer=null,gameStarted=false,playerClass='',facing=new Phaser.Math.Vector2(1,0),lastAttack=0,rangeCircle,hud,radar,level=1,xp=0,points=0,totalDistance=0,hp=100,maxHp=100,playerHpBg,playerHpBar,weapon,statsBtn,invBtn,statPanel=[],invPanel=[],skillBtns=[],lastSkills=[0,0,0];
let stats={str:10,agi:10,vit:10,ene:10};let inventory=[],equipment={head:null,body:null,legs:null,weapon:null};
const classes={Warrior:{color:0xcda85b,range:90,cooldown:520,hp:145,str:18,agi:10,vit:15,ene:5,skills:['Whirlwind','Charge','Guard']},Wizard:{color:0x5b8fc9,range:205,cooldown:650,hp:100,str:5,agi:10,vit:8,ene:22,skills:['Fire Orb','Frost Nova','Lightning']},Archer:{color:0x58a66b,range:235,cooldown:560,hp:115,str:10,agi:20,vit:10,ene:8,skills:['Multi Shot','Piercing','Volley']}};
const tierColors=[0xc8a878,0xa87a55,0x86543f,0x673c34,0x4f2c2c,0x391f24];
function create(){S=this;drawGround(this);showClassSelect(this)}
function drawGround(s){let g=s.add.graphics();g.fillStyle(0x1b2718).fillRect(0,0,960,540);g.lineStyle(1,0x273522,.35);for(let x=0;x<960;x+=32)g.lineBetween(x,0,x,540);for(let y=0;y<540;y+=32)g.lineBetween(0,y,960,y)}
function showClassSelect(s){s.add.rectangle(480,270,700,390,0x080a0e,.94).setStrokeStyle(3,0x8b6b32).setDepth(50);s.add.text(480,115,'CHOOSE YOUR CLASS',{fontFamily:'monospace',fontSize:'28px',color:'#f3d27a'}).setOrigin(.5).setDepth(51);['Warrior','Wizard','Archer'].forEach((c,i)=>{let x=270+i*210,b=s.add.circle(x,260,70,classes[c].color).setStrokeStyle(5,0x493a20).setDepth(51).setInteractive();s.add.text(x,355,c+'\n'+classes[c].skills.join(' • '),{align:'center',fontFamily:'monospace',fontSize:'12px',color:'#fff'}).setOrigin(.5).setDepth(51);b.on('pointerdown',()=>startGame(s,c))})}
function startGame(s,c){playerClass=c;let d=classes[c];maxHp=d.hp;hp=maxHp;stats={str:d.str,agi:d.agi,vit:d.vit,ene:d.ene};inventory=starterItems(c);equipment.weapon=inventory[0];equipment.body=inventory[1];s.children.list.filter(o=>o.depth>=50).forEach(o=>o.destroy());rangeCircle=s.add.circle(480,270,d.range,0x8ab4c8,.035).setStrokeStyle(2,0xb8d9e8,.28);player=s.add.circle(480,270,18,d.color).setStrokeStyle(4,0x352b1c).setDepth(10);weapon=createPlayerWeapon(s);playerHpBg=s.add.rectangle(480,242,66,7,0x2a0909).setDepth(12);playerHpBar=s.add.rectangle(447,242,66,7,0x38b84a).setOrigin(0,.5).setDepth(13);enemies=s.add.group();trees=s.add.group();loots=s.add.group();for(let i=0;i<20;i++)spawnEnemy(s);for(let i=0;i<52;i++)spawnTree(s);spawnLoot(s,true);hud=s.add.text(12,12,'',{fontFamily:'monospace',fontSize:'14px',color:'#f3d27a',backgroundColor:'#111b',padding:{x:6,y:4}}).setDepth(30);radar=s.add.graphics().setDepth(35);setupJoy(s);statsBtn=s.add.text(650,18,'STATS',{fontFamily:'monospace',fontSize:'14px',backgroundColor:'#49391f',padding:{x:8,y:5},color:'#ffd77a'}).setDepth(40).setInteractive();invBtn=s.add.text(735,18,'INVENTORY',{fontFamily:'monospace',fontSize:'14px',backgroundColor:'#2c3c2c',padding:{x:8,y:5},color:'#d9f0cf'}).setDepth(40).setInteractive();statsBtn.on('pointerdown',()=>toggleStats(s));invBtn.on('pointerdown',()=>toggleInventory(s));setupSkills(s);gameStarted=true}
function starterItems(c){let w={name:c==='Warrior'?'Bronze Sword':c==='Wizard'?'Bronze Staff':'Bronze Bow',slot:'weapon',tier:1,power:6,set:'Bronze'},a={name:'Bronze Chest',slot:'body',tier:1,power:4,set:'Bronze'};return[w,a]}
function createPlayerWeapon(s){let g=s.add.graphics().setDepth(11);drawWeapon(g);return g}
function drawWeapon(g){g.clear();if(playerClass==='Warrior'){g.lineStyle(6,0xd7dbe0);g.lineBetween(0,0,30,0);g.lineStyle(4,0x8d5a32);g.lineBetween(-7,0,4,0)}else if(playerClass==='Wizard'){g.lineStyle(6,0x6d4d2c);g.lineBetween(-4,0,31,0);g.fillStyle(0x75d9ff).fillCircle(35,0,7)}else{g.lineStyle(5,0x9b6b3d);g.beginPath();g.arc(7,0,22,-1.25,1.25);g.strokePath();g.lineStyle(2,0xe5d6b0);g.lineBetween(14,-21,14,21)}}
function setupJoy(s){joyBase=s.add.circle(105,435,66,0x000000,.35).setStrokeStyle(3,0x8e7947).setDepth(40);joyKnob=s.add.circle(105,435,29,0xc2a55b,.75).setDepth(41);s.input.addPointer(4);s.input.on('pointerdown',p=>{if(p.x<250&&p.y>285&&joyPointer===null){joyPointer=p.id;setJoy(p)}});s.input.on('pointermove',p=>{if(p.id===joyPointer&&p.isDown)setJoy(p)});s.input.on('pointerup',p=>{if(p.id===joyPointer)resetJoy()});s.input.on('pointerupoutside',p=>{if(p.id===joyPointer)resetJoy()})}
function resetJoy(){joyPointer=null;joyDir.set(0,0);joyKnob&&joyKnob.setPosition(105,435)}function setJoy(p){let d=new Phaser.Math.Vector2(p.x-105,p.y-435);if(d.length()>58)d.setLength(58);joyKnob.setPosition(105+d.x,435+d.y);joyDir.copy(d).scale(1/58)}
function setupSkills(s){skillBtns.forEach(x=>x.destroy());skillBtns=[];classes[playerClass].skills.forEach((name,i)=>{let x=690+i*82,y=474,b=s.add.circle(x,y,31,[0x6f4a2b,0x355b73,0x5b345f][i],.9).setStrokeStyle(2,0xc4a56a).setDepth(42).setInteractive(),t=s.add.text(x,y,name,{fontFamily:'monospace',fontSize:'9px',align:'center',wordWrap:{width:55},color:'#fff'}).setOrigin(.5).setDepth(43);b.on('pointerdown',()=>useSkill(s,i));skillBtns.push(b,t)})}
function currentZone(){return 1+Math.floor(totalDistance/1300)}function monsterLevel(){return Math.min(60,currentZone()+Phaser.Math.Between(0,2))}
function spawnEnemy(s,boss=false){let lv=boss?Math.max(10,currentZone()*5):monsterLevel(),tier=Math.min(5,Math.floor((lv-1)/10)),col=tierColors[tier],e=s.add.circle(Phaser.Math.Between(55,905),Phaser.Math.Between(60,500),boss?23:14+Math.min(6,tier),col).setStrokeStyle(3,boss?0xa26cf2:0x281315).setDepth(5);e.lv=lv;e.boss=boss;e.maxHp=(boss?6:1)*(45+lv*24);e.hp=e.maxHp;e.damage=(boss?2:1)*(4+lv*2);e.attackRange=lv<=10?32:48+Math.min(25,lv);e.nextHit=0;e.weapon=null;e.ring=s.add.circle(e.x,e.y,e.attackRange,0xd54a4a,.018).setStrokeStyle(1,0xe46969,.18).setDepth(3);if(lv>10){e.weapon=s.add.rectangle(e.x+18,e.y,24,5,0x8d7354).setDepth(6);e.weapon.rotation=.2}e.label=s.add.text(e.x,e.y-(boss?40:31),(boss?'BOSS ':'')+`Lv.${lv}`,{fontFamily:'monospace',fontSize:boss?'11px':'10px',color:boss?'#e6b6ff':'#fff'}).setOrigin(.5).setDepth(7);e.hpBg=s.add.rectangle(e.x,e.y-21,boss?58:42,5,0x210808).setDepth(7);e.hpBar=s.add.rectangle(e.x-(boss?29:21),e.y-21,boss?58:42,5,boss?0x9b4fd1:0xd04444).setOrigin(0,.5).setDepth(8);enemies.add(e)}
function spawnTree(s){let x=Phaser.Math.Between(30,930),y=Phaser.Math.Between(55,520),t=s.add.container(x,y).setDepth(2);t.add([s.add.rectangle(0,10,8,18,0x5a3822),s.add.circle(0,0,Phaser.Math.Between(15,22),Phaser.Utils.Array.GetRandom([0x244c2a,0x2e5c32,0x356b38])).setStrokeStyle(3,0x17351d)]);trees.add(t)}
function spawnLoot(s,starter=false){let z=currentZone(),tier=starter?1:Math.min(5,1+Math.floor(z/3)+Phaser.Math.Between(0,1)),slots=['head','body','legs','weapon'],slot=Phaser.Utils.Array.GetRandom(slots),names={head:'Helm',body:'Armor',legs:'Leggings',weapon:playerClass==='Warrior'?'Sword':playerClass==='Wizard'?'Staff':'Bow'},item={name:(tierNames[tier]||'Dark')+' '+names[slot],slot,tier,power:3+tier*5,set:tier>=3?'Dusk':'Bronze'};let l=s.add.circle(Phaser.Math.Between(80,880),Phaser.Math.Between(80,470),9,itemColor(tier)).setStrokeStyle(2,0xf2d17c).setDepth(4);l.item=item;l.label=s.add.text(l.x,l.y-18,'LOOT',{fontFamily:'monospace',fontSize:'9px',color:'#ffd66b'}).setOrigin(.5).setDepth(5);loots.add(l)}
const tierNames=['','Bronze','Iron','Steel','Shadow','Obsidian'];function itemColor(t){return [0,0xb77943,0x7a7f82,0x5d6870,0x3b4050,0x201f2c][t]||0x201f2c}
function update(time,delta){if(!gameStarted)return;if(joyDir.lengthSq()>.015){let v=joyDir.clone();facing.copy(v).normalize();let speed=(.18+stats.agi*.0035)*Math.min(delta,33),px=v.x*speed,py=v.y*speed;totalDistance+=Math.hypot(px,py);moveWorld(-px,-py)}let target=nearest();if(target&&time-lastAttack>classes[playerClass].cooldown){lastAttack=time;basicAttack(this,target)}placePlayerWeapon();enemies.children.iterate(e=>{if(!e)return;let d=Phaser.Math.Distance.Between(480,270,e.x,e.y);if(d<205){let dir=new Phaser.Math.Vector2(480-e.x,270-e.y).normalize();e.x+=dir.x*.35;e.y+=dir.y*.35;if(e.weapon){e.weapon.x=e.x+dir.x*18;e.weapon.y=e.y+dir.y*18;e.weapon.rotation=dir.angle()}updateEnemyUI(e);if(d<e.attackRange&&time>e.nextHit){e.nextHit=time+900;monsterAttackAnim(e);hp=Math.max(0,hp-e.damage);if(hp<=0){hp=maxHp;totalDistance=Math.max(0,totalDistance-900)}}}});loots.children.iterate(l=>{if(l&&Phaser.Math.Distance.Between(480,270,l.x,l.y)<30){inventory.push(l.item);l.label.destroy();l.destroy();if(inventory.length<10)spawnLoot(this)}});if(currentZone()%4===0&&!enemies.getChildren().some(e=>e.boss))spawnEnemy(this,true);if(loots.getLength()<3)spawnLoot(this);playerHpBar.displayWidth=66*(hp/maxHp);drawRadar();hud.setText(`${playerClass.toUpperCase()}  LV ${level}  HP ${Math.ceil(hp)}/${maxHp}  XP ${xp}/${level*100}  PTS ${points}  ZONE ${currentZone()}\nSTR ${stats.str} AGI ${stats.agi} VIT ${stats.vit} ENE ${stats.ene}${setBonus()?'  • FULL SET BONUS':''}`)}
function moveWorld(dx,dy){enemies.children.iterate(e=>{if(!e)return;e.x+=dx;e.y+=dy;if(e.x<-80)e.x=1040;if(e.x>1040)e.x=-80;if(e.y<-80)e.y=620;if(e.y>620)e.y=-80;updateEnemyUI(e)});trees.children.iterate(t=>{t.x+=dx;t.y+=dy;if(t.x<-50)t.x=1010;if(t.x>1010)t.x=-50;if(t.y<-50)t.y=590;if(t.y>590)t.y=-50});loots.children.iterate(l=>{if(!l)return;l.x+=dx;l.y+=dy;l.label.setPosition(l.x,l.y-18)})}
function updateEnemyUI(e){e.label.setPosition(e.x,e.y-(e.boss?40:31));e.hpBg.setPosition(e.x,e.y-21);let w=e.boss?58:42;e.hpBar.setPosition(e.x-w/2,e.y-21);e.hpBar.displayWidth=w*Math.max(0,e.hp/e.maxHp);e.ring.setPosition(e.x,e.y);if(e.weapon){e.weapon.x=e.x+18;e.weapon.y=e.y}}
function nearest(){let best=null,bd=classes[playerClass].range;enemies.children.iterate(e=>{let d=Phaser.Math.Distance.Between(480,270,e.x,e.y);if(d<bd){bd=d;best=e}});return best}
function totalPower(){let p=0;Object.values(equipment).forEach(i=>{if(i)p+=i.power});if(setBonus())p+=12;return p}function setBonus(){let a=[equipment.head,equipment.body,equipment.legs].filter(Boolean);return a.length===3&&a.every(i=>i.set===a[0].set)}
function basicAttack(s,t){let base=playerClass==='Warrior'?14+stats.str:playerClass==='Wizard'?10+stats.ene*1.55:10+stats.agi*1.25,dmg=base+totalPower();animatePlayerWeapon(s,t);if(playerClass==='Warrior'){s.time.delayedCall(110,()=>{if(t.active){t.hp-=dmg;hit(s,t)}})}else{let p=playerClass==='Wizard'?s.add.circle(480,270,8,0x76d9ff).setDepth(15):s.add.rectangle(480,270,25,4,0xe8d29a).setDepth(15);p.rotation=Phaser.Math.Angle.Between(480,270,t.x,t.y);s.tweens.add({targets:p,x:t.x,y:t.y,duration:250,onComplete:()=>{if(t.active){t.hp-=dmg;hit(s,t)}p.destroy()}})}}
function animatePlayerWeapon(s,t){facing.set(t.x-480,t.y-270).normalize();if(playerClass==='Warrior')s.tweens.add({targets:weapon,rotation:facing.angle()-.7,duration:70,yoyo:true});else if(playerClass==='Wizard')s.tweens.add({targets:weapon,scaleX:1.22,scaleY:1.22,duration:90,yoyo:true});else s.tweens.add({targets:weapon,scaleY:.7,duration:80,yoyo:true})}
function monsterAttackAnim(e){if(!e.weapon)return;S.tweens.add({targets:e.weapon,rotation:e.weapon.rotation+.8,duration:100,yoyo:true})}
function placePlayerWeapon(){weapon.setPosition(480+facing.x*23,270+facing.y*23);weapon.rotation=facing.angle()}
function hit(s,e){if(e.hp<=0){let reward=(20+e.lv*7)*(e.boss?5:1);destroyEnemy(e);xp+=reward;while(xp>=level*100){xp-=level*100;level++;points+=5;hp=maxHp}if(e.boss||Math.random()<.28)spawnLoot(s);s.time.delayedCall(650,()=>spawnEnemy(s))}else updateEnemyUI(e)}function destroyEnemy(e){[e.label,e.hpBg,e.hpBar,e.ring,e.weapon].forEach(o=>o&&o.destroy());e.destroy()}
function useSkill(s,i){let now=s.time.now;if(now-lastSkills[i]<(2600+i*800))return;lastSkills[i]=now;let dmg=(18+i*10)+totalPower()+stats.ene*.8+stats.str*.5+stats.agi*.5;if(playerClass==='Warrior'){if(i===1){let t=nearest();if(t){facing.set(t.x-480,t.y-270).normalize();moveWorld(-facing.x*55,-facing.y*55)}}enemies.children.iterate(e=>{if(Phaser.Math.Distance.Between(480,270,e.x,e.y)<(110+i*25)){e.hp-=dmg;hit(s,e)}});let r=s.add.circle(480,270,35,0xe5a65b,.15).setStrokeStyle(4,0xe5a65b).setDepth(14);s.tweens.add({targets:r,scale:3,alpha:0,duration:300,onComplete:()=>r.destroy()})}else if(playerClass==='Wizard'){enemies.children.iterate(e=>{let d=Phaser.Math.Distance.Between(480,270,e.x,e.y);if(d<220){e.hp-=dmg*(i===2?1.35:1);hit(s,e)}});let col=[0xff7b42,0x79d8ff,0xe8e46b][i],r=s.add.circle(480,270,25,col,.18).setStrokeStyle(4,col).setDepth(14);s.tweens.add({targets:r,scale:5,alpha:0,duration:380,onComplete:()=>r.destroy()})}else{let targets=enemies.getChildren().filter(e=>Phaser.Math.Distance.Between(480,270,e.x,e.y)<260).slice(0,3+i*2);targets.forEach((e,n)=>s.time.delayedCall(n*70,()=>{if(e.active){let a=s.add.rectangle(480,270,22,3,0xf0d8a4).setDepth(15);a.rotation=Phaser.Math.Angle.Between(480,270,e.x,e.y);s.tweens.add({targets:a,x:e.x,y:e.y,duration:220,onComplete:()=>{if(e.active){e.hp-=dmg;hit(s,e)}a.destroy()}})}}))}}
function toggleStats(s){clearPanels();let bg=s.add.rectangle(810,190,270,230,0x090b10,.97).setStrokeStyle(2,0x8b6b32).setDepth(50),title=s.add.text(690,88,`CHARACTER • POINTS ${points}`,{fontFamily:'monospace',fontSize:'15px',color:'#f3d27a'}).setDepth(51);statPanel=[bg,title];[['STR','str'],['AGI','agi'],['VIT','vit'],['ENE','ene']].forEach((v,i)=>{let y=125+i*36,t=s.add.text(690,y,`${v[0]} ${stats[v[1]]}`,{fontFamily:'monospace',fontSize:'15px',color:'#fff'}).setDepth(51),b=s.add.text(880,y,'+',{fontFamily:'monospace',fontSize:'19px',backgroundColor:'#59451f',padding:{x:8,y:1},color:'#ffd77a'}).setDepth(51).setInteractive();b.on('pointerdown',()=>{if(points>0){points--;stats[v[1]]++;if(v[1]==='vit'){maxHp+=4;hp+=4}toggleStats(s)}});statPanel.push(t,b)});statPanel.push(s.add.text(690,275,`POWER ${totalPower()}\nSET ${setBonus()?'ACTIVE +12':'none'}`,{fontFamily:'monospace',fontSize:'13px',color:'#aee0a0'}).setDepth(51))}
function toggleInventory(s){clearPanels();let bg=s.add.rectangle(760,250,390,440,0x090b10,.97).setStrokeStyle(2,0x61704f).setDepth(50),title=s.add.text(590,48,'INVENTORY / EQUIPMENT',{fontFamily:'monospace',fontSize:'16px',color:'#d8e8c9'}).setDepth(51);invPanel=[bg,title];let slots=['head','body','legs','weapon'];slots.forEach((sl,i)=>invPanel.push(s.add.text(590,82+i*30,`${sl.toUpperCase()}: ${equipment[sl]?equipment[sl].name:'empty'}`,{fontFamily:'monospace',fontSize:'12px',color:equipment[sl]?colorHex(equipment[sl].tier):'#777'}).setDepth(51)));inventory.slice(0,10).forEach((it,i)=>{let y=220+i*25,t=s.add.text(590,y,`${it.name}  +${it.power}`,{fontFamily:'monospace',fontSize:'12px',color:colorHex(it.tier),backgroundColor:'#151b15',padding:{x:5,y:2}}).setDepth(51).setInteractive();t.on('pointerdown',()=>{equipment[it.slot]=it;toggleInventory(s)});invPanel.push(t)})}
function colorHex(t){return ['#777','#c58a55','#a8afb4','#86939c','#626b82','#343448'][t]||'#fff'}function clearPanels(){[...statPanel,...invPanel].forEach(o=>o&&o.destroy());statPanel=[];invPanel=[]}
function drawRadar(){radar.clear();radar.fillStyle(0x05080a,.84).fillCircle(875,90,64);radar.lineStyle(3,0x9a8149,.9).strokeCircle(875,90,64);radar.fillStyle(0x52d66b).fillCircle(875,90,4);enemies.children.iterate(e=>{let dx=(e.x-480)*.2,dy=(e.y-270)*.2,d=Math.hypot(dx,dy);if(d>57){dx*=57/d;dy*=57/d}radar.fillStyle(e.boss?0xb660ff:0xe44b4b).fillCircle(875+dx,90+dy,e.boss?5:3)});loots.children.iterate(l=>{let dx=(l.x-480)*.2,dy=(l.y-270)*.2,d=Math.hypot(dx,dy);if(d>57){dx*=57/d;dy*=57/d}radar.fillStyle(0xffd34d).fillCircle(875+dx,90+dy,4)})}
