const LOOTBORN_REWORK='v0.11.0-alpha';
let killStreak=0,lastKillAt=0;
function rarityName(t){return ['Common','Bronze','Iron','Steel','Shadow','Obsidian'][t]||'Ancient'}
function lootBurst(s,x,y,item){const col=itemColor(item.tier);for(let i=0;i<8;i++){let p=s.add.circle(x,y,Phaser.Math.Between(2,4),col,.9).setDepth(18);let a=Math.PI*2*i/8,d=Phaser.Math.Between(20,46);s.tweens.add({targets:p,x:x+Math.cos(a)*d,y:y+Math.sin(a)*d,alpha:0,duration:420,onComplete:()=>p.destroy()})}let beam=s.add.rectangle(x,y-24,3,48,col,.65).setDepth(12);s.tweens.add({targets:beam,alpha:0,scaleY:1.7,duration:650,onComplete:()=>beam.destroy()})}
const _spawnLoot=spawnLoot;spawnLoot=function(s,starter=false){_spawnLoot(s,starter);let l=loots.getChildren().at(-1);if(l&&l.item){l.item.rarity=rarityName(l.item.tier);lootBurst(s,l.x,l.y,l.item);if(l.label)l.label.setText(`${l.item.rarity} ${l.item.name} +${l.item.power}`)}};
const _destroyEnemy=destroyEnemy;destroyEnemy=function(e){let x=e.x,y=e.y,b=e.boss;_destroyEnemy(e);let now=S.time.now;killStreak=now-lastKillAt<2200?killStreak+1:1;lastKillAt=now;let txt=S.add.text(x,y-18,b?'BOSS SLAIN!':`${killStreak} KILL`,{fontFamily:'Georgia',fontSize:b?'18px':'12px',fontStyle:'bold',color:b?'#e8bcff':'#e6c978',stroke:'#160d08',strokeThickness:3}).setOrigin(.5).setDepth(20);S.tweens.add({targets:txt,y:y-48,alpha:0,duration:800,onComplete:()=>txt.destroy()})};
const _spawnEnemy=spawnEnemy;spawnEnemy=function(s,boss=false){_spawnEnemy(s,boss);let e=enemies.getChildren().at(-1);if(!e)return;let elite=!boss&&e.lv>=8&&Math.random()<.18;if(elite){e.elite=true;e.maxHp*=2.4;e.hp=e.maxHp;e.damage*=1.55;e.setScale(1.18);e.setStrokeStyle(4,0xd8a64c);e.label.setText(`ELITE Lv.${e.lv}`).setColor('#ffd477');e.ring.setStrokeStyle(2,0xe0a947,.35)}};
function spawnPack(s,count=3){for(let i=0;i<count;i++)s.time.delayedCall(i*120,()=>spawnEnemy(s,false))}
const _hit=hit;hit=function(s,e){let was=e.active&&e.hp<=0,elite=e.elite,boss=e.boss,x=e.x,y=e.y;_hit(s,e);if(was&&(elite||boss)){s.time.delayedCall(120,()=>spawnLoot(s));if(boss)s.time.delayedCall(260,()=>spawnLoot(s));}if(was&&enemies.getLength()<6)spawnPack(s,Phaser.Math.Between(2,4))};
setTimeout(()=>{let el=document.querySelector('.mmo-version');if(el)el.textContent=LOOTBORN_REWORK},0);